# Generated by Django 5.0 on 2023-12-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Slug of the product', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=5)),
                ('images', models.ImageField(help_text='Image of the product', upload_to='photos/products/')),
                ('stock', models.IntegerField(help_text='Stock of the product', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Availability of the product', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category of the product', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-id',),
            },
        ),
    ]
