# Generated by Django 5.0 on 2023-12-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
